/**
 * Seed menus
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('menus').del();

  // Insert seed entries
  await knex('menus').insert([
    // 外部页面
    { id: 100, parent_id: 0, menu_type: 0, title: 'menus.pureExternalPage', name: 'PureIframe', path: '/iframe', component: '', rank: 7, redirect: '', icon: 'ri:links-fill', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 101, parent_id: 100, menu_type: 0, title: 'menus.pureExternalDoc', name: 'PureIframeExternal', path: '/iframe/external', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 102, parent_id: 101, menu_type: 2, title: 'menus.pureExternalLink', name: 'https://pure-admin.cn/', path: '/external', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 103, parent_id: 101, menu_type: 2, title: 'menus.pureUtilsLink', name: 'https://pure-admin-utils.netlify.app/', path: '/pureUtilsLink', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 104, parent_id: 100, menu_type: 1, title: 'menus.pureEmbeddedDoc', name: 'PureIframeEmbedded', path: '/iframe/embedded', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 105, parent_id: 104, menu_type: 1, title: 'menus.pureEpDoc', name: 'FrameEp', path: '/iframe/ep', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: 'https://element-plus.org/zh-CN/', frame_loading: true, keep_alive: true, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 106, parent_id: 104, menu_type: 1, title: 'menus.pureTailwindcssDoc', name: 'FrameTailwindcss', path: '/iframe/tailwindcss', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: 'https://tailwindcss.com/docs/installation', frame_loading: true, keep_alive: true, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 107, parent_id: 104, menu_type: 1, title: 'menus.pureVueDoc', name: 'FrameVue', path: '/iframe/vue3', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: 'https://cn.vuejs.org/', frame_loading: true, keep_alive: true, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 108, parent_id: 104, menu_type: 1, title: 'menus.pureViteDoc', name: 'FrameVite', path: '/iframe/vite', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: 'https://cn.vitejs.dev/', frame_loading: true, keep_alive: true, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 109, parent_id: 104, menu_type: 1, title: 'menus.purePiniaDoc', name: 'FramePinia', path: '/iframe/pinia', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: 'https://pinia.vuejs.org/zh/index.html', frame_loading: true, keep_alive: true, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 110, parent_id: 104, menu_type: 1, title: 'menus.pureRouterDoc', name: 'FrameRouter', path: '/iframe/vue-router', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: 'https://router.vuejs.org/zh/', frame_loading: true, keep_alive: true, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    // 权限管理
    { id: 200, parent_id: 0, menu_type: 0, title: 'menus.purePermission', name: 'PurePermission', path: '/permission', component: '', rank: 9, redirect: '', icon: 'ep:lollipop', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 201, parent_id: 200, menu_type: 0, title: 'menus.purePermissionPage', name: 'PermissionPage', path: '/permission/page/index', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 202, parent_id: 200, menu_type: 0, title: 'menus.purePermissionButton', name: 'PermissionButton', path: '/permission/button', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 203, parent_id: 202, menu_type: 0, title: 'menus.purePermissionButtonRouter', name: 'PermissionButtonRouter', path: '/permission/button/router', component: 'permission/button/index', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 210, parent_id: 203, menu_type: 3, title: '添加', name: '', path: '', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: 'permission:btn:add', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 211, parent_id: 203, menu_type: 3, title: '修改', name: '', path: '', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: 'permission:btn:edit', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 212, parent_id: 203, menu_type: 3, title: '删除', name: '', path: '', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: 'permission:btn:delete', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 204, parent_id: 202, menu_type: 0, title: 'menus.purePermissionButtonLogin', name: 'PermissionButtonLogin', path: '/permission/button/login', component: 'permission/button/perms', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 220, parent_id: 204, menu_type: 3, title: '添加', name: '', path: '', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: 'permission:btn:add', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 221, parent_id: 204, menu_type: 3, title: '修改', name: '', path: '', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: 'permission:btn:edit', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 222, parent_id: 204, menu_type: 3, title: '删除', name: '', path: '', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: 'permission:btn:delete', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    // 系统管理
    { id: 300, parent_id: 0, menu_type: 0, title: 'menus.pureSysManagement', name: 'PureSystem', path: '/system', component: '', rank: 10, redirect: '', icon: 'ri:settings-3-line', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 301, parent_id: 300, menu_type: 0, title: 'menus.pureUser', name: 'SystemUser', path: '/system/user/index', component: '', rank: null, redirect: '', icon: 'ri:admin-line', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 302, parent_id: 300, menu_type: 0, title: 'menus.pureRole', name: 'SystemRole', path: '/system/role/index', component: '', rank: null, redirect: '', icon: 'ri:admin-fill', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 303, parent_id: 300, menu_type: 0, title: 'menus.pureSystemMenu', name: 'SystemMenu', path: '/system/menu/index', component: '', rank: null, redirect: '', icon: 'ep:menu', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 304, parent_id: 300, menu_type: 0, title: 'menus.pureDept', name: 'SystemDept', path: '/system/dept/index', component: '', rank: null, redirect: '', icon: 'ri:git-branch-line', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    // 系统监控
    { id: 400, parent_id: 0, menu_type: 0, title: 'menus.pureSysMonitor', name: 'PureMonitor', path: '/monitor', component: '', rank: 11, redirect: '', icon: 'ep:monitor', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 401, parent_id: 400, menu_type: 0, title: 'menus.pureOnlineUser', name: 'OnlineUser', path: '/monitor/online-user', component: 'monitor/online/index', rank: null, redirect: '', icon: 'ri:user-voice-line', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 402, parent_id: 400, menu_type: 0, title: 'menus.pureLoginLog', name: 'LoginLog', path: '/monitor/login-logs', component: 'monitor/logs/login/index', rank: null, redirect: '', icon: 'ri:window-line', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 403, parent_id: 400, menu_type: 0, title: 'menus.pureOperationLog', name: 'OperationLog', path: '/monitor/operation-logs', component: 'monitor/logs/operation/index', rank: null, redirect: '', icon: 'ri:history-fill', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 404, parent_id: 400, menu_type: 0, title: 'menus.pureSystemLog', name: 'SystemLog', path: '/monitor/system-logs', component: 'monitor/logs/system/index', rank: null, redirect: '', icon: 'ri:file-search-line', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    // 标签页操作
    { id: 500, parent_id: 0, menu_type: 0, title: 'menus.pureTabs', name: 'PureTabs', path: '/tabs', component: '', rank: 12, redirect: '', icon: 'ri:bookmark-2-line', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 501, parent_id: 500, menu_type: 0, title: 'menus.pureTabs', name: 'Tabs', path: '/tabs/index', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: true, show_parent: false },
    { id: 502, parent_id: 500, menu_type: 0, title: 'query传参模式', name: 'TabQueryDetail', path: '/tabs/query-detail', component: '', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '/tabs/index', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: false, show_parent: false },
    { id: 503, parent_id: 500, menu_type: 0, title: 'params传参模式', name: 'TabParamsDetail', path: '/tabs/params-detail/:id', component: 'params-detail', rank: null, redirect: '', icon: '', extra_icon: '', enter_transition: '', leave_transition: '', active_path: '/tabs/index', auths: '', frame_src: '', frame_loading: true, keep_alive: false, hidden_tag: false, fixed_tag: false, show_link: false, show_parent: false }
  ]);
}
